@extends('errors.layout')
@section('code', '404')
@section('title', 'Halaman tidak ditemukan')
@section('message', 'Alamat yang dibuka mungkin salah, sudah berubah, atau halaman tersebut tidak lagi tersedia.')
@section('hint', 'Periksa kembali alamat halaman atau gunakan menu utama untuk menemukan informasi yang dibutuhkan.')
