@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<div class="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-teal-700">Tahun pelajaran {{ $year?->name ?? 'belum aktif' }}</p><h1 class="mt-1 text-3xl font-bold">Dashboard BK</h1><p class="mt-2 text-sm text-slate-500">Pantau prioritas penanganan dan administrasi terbaru.</p></div><a class="btn btn-primary" href="{{ route('cases.create') }}">+ Catat pelanggaran</a></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="stat"><p class="stat-label">Siswa aktif</p><p class="stat-value">{{ number_format($students) }}</p></div><div class="stat"><p class="stat-label">Kasus hari ini</p><p class="stat-value">{{ $todayCases }}</p></div><div class="stat"><p class="stat-label">Kasus bulan ini</p><p class="stat-value">{{ $monthCases }}</p></div><div class="stat"><p class="stat-label">Belum selesai</p><p class="stat-value text-orange-600">{{ $openCases }}</p></div></div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section class="card"><div class="card-body flex items-center justify-between"><div><h2 class="text-lg font-bold">Siswa prioritas</h2><p class="text-sm text-slate-500">Berdasarkan total poin tahun aktif</p></div><a class="text-sm font-semibold text-teal-700" href="{{ route('students.index') }}">Lihat siswa</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Siswa</th><th>Kelas</th><th class="text-right">Poin</th></tr></thead><tbody>@forelse($priority as $student)<tr><td><a class="font-semibold text-navy-900 hover:text-teal-700" href="{{ route('students.show',$student) }}">{{ $student->name }}</a><p class="text-xs text-slate-400">{{ $student->nisn ?: ($student->nis ?: $student->temporary_id) }}</p></td><td>{{ $student->currentEnrollment?->schoolClass?->name ?? '-' }}</td><td class="text-right"><span class="badge {{ $student->annual_points>=75?'badge-red':($student->annual_points>=50?'badge-orange':'badge-amber') }}">{{ $student->annual_points }}</span></td></tr>@empty<tr><td colspan="3" class="text-center text-slate-400">Belum ada pelanggaran pada tahun aktif.</td></tr>@endforelse</tbody></table></div></section>
<div class="space-y-6"><section class="card card-body"><h2 class="text-lg font-bold">Pelanggaran terbanyak</h2><div class="mt-5 space-y-4">@forelse($topInstruments as $item)<div><div class="flex justify-between gap-4 text-sm"><span class="line-clamp-1">{{ $item->name }}</span><strong>{{ $item->total }}</strong></div><div class="mt-2 h-1.5 rounded-full bg-slate-100"><div class="h-1.5 rounded-full bg-teal-500" style="width:{{ min(100,$item->total*10) }}%"></div></div></div>@empty<p class="text-sm text-slate-400">Belum ada data.</p>@endforelse</div></section><section class="card card-body"><h2 class="text-lg font-bold">Tindak lanjut mendatang</h2><div class="mt-4 space-y-3">@forelse($followUps as $follow)<div class="rounded-xl bg-slate-50 p-3 text-sm"><strong>{{ $follow->type->label() }}</strong><p class="mt-1 text-slate-500">{{ $follow->scheduled_at?->translatedFormat('d M Y') ?? 'Belum dijadwalkan' }}</p></div>@empty<p class="text-sm text-slate-400">Tidak ada agenda.</p>@endforelse</div></section></div></div>
@if(auth()->user()->role === \App\Enums\UserRole::SuperAdmin)
<section class="card card-body mt-6"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 class="text-lg font-bold">Status backup</h2><p class="mt-1 text-sm text-slate-500">Backup database dan arsip privat terenkripsi di penyimpanan luar VPS.</p></div>@if($backupStatus)<div class="text-left sm:text-right"><span class="badge {{ ($backupStatus['successful'] ?? false)?'badge-emerald':'badge-red' }}">{{ ($backupStatus['successful'] ?? false)?'Berhasil':'Gagal' }}</span><p class="mt-2 text-xs text-slate-500">{{ \Illuminate\Support\Carbon::parse($backupStatus['finished_at'])->translatedFormat('d M Y H:i') }}</p></div>@else<span class="badge badge-amber">Belum pernah dijalankan</span>@endif</div></section>
@endif
<div class="mt-6 grid gap-6 xl:grid-cols-3"><section class="card card-body"><h2 class="text-lg font-bold">Tingkat prioritas</h2><div class="mt-4 space-y-3">@foreach($severityCounts as $level)<div class="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm"><span>{{ $level['name'] }}</span><span class="badge badge-{{ $level['color'] }}">{{ $level['total'] }} siswa</span></div>@endforeach</div></section><section class="card card-body"><h2 class="text-lg font-bold">Distribusi kelas</h2><div class="mt-4 max-h-72 space-y-2 overflow-y-auto">@foreach($classDistribution as $class)<div class="flex justify-between border-b border-slate-100 py-2 text-sm"><span>{{ $class->name }}</span><strong>{{ $class->total }}</strong></div>@endforeach</div></section><section class="card card-body"><h2 class="text-lg font-bold">Aktivitas terbaru</h2><div class="mt-4 space-y-3">@forelse($recentActivities as $activity)<div class="border-b border-slate-100 pb-3 text-sm"><strong>{{ $activity->user?->name ?? 'Sistem' }}</strong><p class="text-slate-500">{{ $activity->action }}</p><p class="mt-1 text-xs text-slate-400">{{ $activity->created_at->diffForHumans() }}</p></div>@empty<p class="text-sm text-slate-400">Belum ada aktivitas.</p>@endforelse</div></section></div>
@endsection
