@extends('layouts.app')
@section('title','Master Data')
@section('content')
<div class="mb-7"><h1 class="text-3xl font-bold">Master data</h1><p class="mt-2 text-sm text-slate-500">Tahun pelajaran, kelas, akun guru BK, dan kelas binaan.</p></div>
<div class="grid gap-6 xl:grid-cols-3"><section class="card card-body"><h2 class="text-lg font-bold">Tahun pelajaran</h2><form method="post" action="{{ route('master.year') }}" class="mt-4 space-y-3">@csrf<input class="form-control" name="name" placeholder="2027/2028" required><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="is_active" value="1"> Jadikan tahun aktif</label><button class="btn btn-primary w-full">Tambah tahun</button></form><div class="mt-5 space-y-2">@foreach($years as $year)<div class="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{{ $year->name }}</span>@if($year->is_active)<span class="badge badge-emerald">Aktif</span>@endif</div>@endforeach</div></section>
<section class="card card-body"><h2 class="text-lg font-bold">Tambah kelas</h2><form method="post" action="{{ route('master.class') }}" class="mt-4 space-y-3">@csrf<select class="form-select" name="academic_year_id">@foreach($years as $year)<option value="{{ $year->id }}">{{ $year->name }}</option>@endforeach</select><input class="form-control" name="name" placeholder="Contoh: XI-SAINS 1" required><div class="grid grid-cols-2 gap-3"><select class="form-select" name="grade_level"><option>X</option><option>XI</option><option>XII</option></select><input class="form-control" name="group_number" type="number" min="1" placeholder="Rombel"></div><input class="form-control" name="track" placeholder="Peminatan (opsional)"><select class="form-select" name="homeroom_teacher_id"><option value="">Wali kelas belum ditentukan</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->name }}</option>@endforeach</select><button class="btn btn-primary w-full">Tambah kelas</button></form></section>
<section class="card card-body"><h2 class="text-lg font-bold">Akun guru BK</h2><form method="post" action="{{ route('master.teacher') }}" class="mt-4 space-y-3">@csrf<input class="form-control" name="name" placeholder="Nama lengkap" required><input class="form-control" name="nip" placeholder="NIP (opsional)"><input class="form-control" name="phone" placeholder="Nomor telepon"><input class="form-control" name="username" placeholder="Username" required><select class="form-select" name="role"><option value="guru_bk">Guru BK</option><option value="coordinator_bk">Koordinator BK</option></select><input class="form-control" type="password" name="password" placeholder="Kata sandi awal (min. 8)" required><button class="btn btn-accent w-full">Buat akun</button></form></section></div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card"><div class="card-body"><h2 class="text-lg font-bold">Daftar kelas</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Kelas</th><th>Tahun</th><th>Wali kelas</th><th>Siswa</th></tr></thead><tbody>@foreach($classes as $class)<tr><td><strong>{{ $class->name }}</strong></td><td>{{ $class->academicYear->name }}</td><td>{{ $class->homeroomTeacher?->name ?? '-' }}</td><td>{{ $class->enrollments()->count() }}</td></tr>@endforeach</tbody></table></div></section>
<section class="card"><div class="card-body"><h2 class="text-lg font-bold">Kelas binaan guru BK</h2></div><div class="divide-y divide-slate-100">@foreach($teachers as $teacher)<form method="post" action="{{ route('master.assign') }}" class="p-5">@csrf<input type="hidden" name="teacher_id" value="{{ $teacher->id }}"><strong>{{ $teacher->name }}</strong><p class="text-xs text-slate-400">{{ $teacher->nip ?: 'NIP belum diisi' }}</p><div class="mt-3 grid max-h-40 gap-2 overflow-y-auto sm:grid-cols-2">@foreach($classes as $class)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="class_ids[]" value="{{ $class->id }}" @checked($teacher->assignedClasses->contains($class->id))>{{ $class->name }}</label>@endforeach</div><button class="btn btn-secondary mt-4">Simpan binaan</button></form>@endforeach</div></section></div>
@if(auth()->user()->role===\App\Enums\UserRole::SuperAdmin)
<section class="card mt-6"><div class="card-body"><h2 class="text-lg font-bold">Kontrol akun staf</h2><p class="mt-1 text-sm text-slate-500">Ubah peran, aktif/nonaktif, atau berikan kata sandi sementara.</p></div><div class="divide-y divide-slate-100">@foreach($users as $staff)<form method="post" action="{{ route('accounts.update',$staff) }}" class="grid gap-3 p-5 md:grid-cols-[1fr_180px_220px_auto] md:items-end">@csrf @method('put')<div><strong>{{ $staff->name }}</strong><p class="text-xs text-slate-400">{{ $staff->username }}</p><label class="mt-2 flex items-center gap-2 text-xs"><input type="checkbox" name="is_active" value="1" @checked($staff->is_active)> Akun aktif</label></div><div><label class="form-label">Peran</label><select class="form-select" name="role"><option value="super_admin" @selected($staff->role===\App\Enums\UserRole::SuperAdmin)>Super Admin</option><option value="coordinator_bk" @selected($staff->role===\App\Enums\UserRole::Coordinator)>Koordinator BK</option><option value="guru_bk" @selected($staff->role===\App\Enums\UserRole::Counselor)>Guru BK</option></select></div><div><label class="form-label">Kata sandi baru (opsional)</label><input class="form-control" type="password" name="password" minlength="8" autocomplete="new-password"></div><button class="btn btn-secondary">Simpan akun</button></form>@endforeach</div></section>
@endif
@endsection
