@extends('layouts.app')
@section('title',$case->case_number)
@section('content')
<header class="page-header"><div><a class="back-link" href="{{ route('cases.index') }}"><x-icon name="arrow-left" /> Daftar kasus</a><p class="page-eyebrow"><x-icon name="clipboard" class="size-4" /> Detail kejadian</p><h1 class="page-title">{{ $case->case_number }}</h1><p class="page-description">Dicatat {{ $case->created_at->translatedFormat('d F Y H:i') }} oleh {{ $case->creator->name }}</p></div><span class="badge badge-slate">{{ $case->status->label() }}</span></header>
<div class="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div class="space-y-6"><section class="card card-body"><div class="flex flex-col justify-between gap-4 sm:flex-row"><div><p class="text-sm text-slate-500">Siswa</p><a href="{{ route('students.show',$case->student) }}" class="mt-1 block text-xl font-bold text-navy-900 hover:text-teal-700">{{ $case->student->name }}</a><p class="text-sm text-slate-500">{{ $case->student->currentEnrollment?->schoolClass?->name }} · {{ $case->student->nisn?:($case->student->nis?:$case->student->temporary_id) }}</p></div><div class="text-left sm:text-right"><p class="text-sm text-slate-500">Total poin kejadian</p><p class="text-3xl font-bold text-orange-600">{{ $case->items->sum('points') }}</p></div></div><dl class="mt-6 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-2"><div><dt class="text-xs font-bold uppercase text-slate-400">Waktu</dt><dd class="mt-1 text-sm">{{ $case->occurred_at->translatedFormat('d F Y, H:i') }}</dd></div><div><dt class="text-xs font-bold uppercase text-slate-400">Lokasi</dt><dd class="mt-1 text-sm">{{ $case->location ?: '-' }}</dd></div></dl><div class="mt-5"><p class="text-xs font-bold uppercase text-slate-400">Kronologi</p><p class="mt-2 whitespace-pre-line text-sm leading-7 text-slate-700">{{ $case->chronology }}</p></div></section>
<section class="card"><div class="card-body"><h2 class="text-lg font-bold">Rincian instrumen</h2></div><div class="divide-y divide-slate-100">@foreach($case->items as $item)<div class="p-5"><div class="flex justify-between gap-4"><strong>{{ $item->instrument_code }} · {{ $item->instrument_name }}</strong><span class="badge badge-amber h-fit">{{ $item->points }} poin</span></div><p class="mt-2 text-sm text-slate-500">Sanksi: {{ $item->sanction_snapshot ?: '-' }}</p></div>@endforeach</div></section>
<section class="card"><div class="card-body flex justify-between"><div><h2 class="text-lg font-bold">Lampiran bukti</h2><p class="text-sm text-slate-500">Berkas privat, hanya staf BK.</p></div></div><div class="divide-y divide-slate-100">@forelse($case->attachments as $file)<div class="flex items-center justify-between gap-4 p-4">@if($file->thumbnail_path)<img class="h-16 w-20 rounded-lg object-cover" src="{{ URL::temporarySignedRoute('attachments.download',now()->addMinutes(10),['attachment'=>$file,'thumbnail'=>1]) }}" alt="Pratinjau bukti">@endif<div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">{{ $file->original_name }}</p><p class="text-xs text-slate-400">{{ number_format($file->size/1024,1) }} KB · {{ $file->mime_type }}</p></div><a class="btn btn-secondary" href="{{ URL::temporarySignedRoute('attachments.download',now()->addMinutes(10),['attachment'=>$file]) }}">Unduh</a></div>@empty<p class="p-6 text-sm text-slate-400">Tidak ada lampiran.</p>@endforelse</div></section></div>
<div class="space-y-6"><section class="card card-body"><h2 class="text-lg font-bold">Tindak lanjut</h2><div class="mt-4 space-y-3">@foreach($case->followUps as $follow)<div class="rounded-xl bg-slate-50 p-4"><div class="flex justify-between"><strong class="text-sm">{{ $follow->type->label() }}</strong><span class="badge badge-slate">{{ $follow->status }}</span></div><p class="mt-2 text-sm text-slate-600">{{ $follow->notes ?: 'Tanpa catatan' }}</p><p class="mt-2 text-xs text-slate-400">{{ $follow->scheduled_at?->translatedFormat('d M Y') }} · {{ $follow->creator->name }}</p></div>@endforeach</div>@can('update',$case)<form method="post" action="{{ route('cases.follow-up',$case) }}" class="mt-5 space-y-3 border-t border-slate-200 pt-5">@csrf<select class="form-select" name="type" required>@foreach(\App\Enums\FollowUpType::cases() as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</select><div class="grid gap-3 sm:grid-cols-2"><input class="form-control" type="date" name="scheduled_at"><select class="form-select" name="status"><option value="planned">Direncanakan</option><option value="completed">Selesai</option></select></div><input class="form-control" name="parent_name" placeholder="Nama orang tua (opsional)"><input class="form-control" name="parent_contact" placeholder="Kontak (opsional)"><textarea class="form-control" name="notes" rows="3" placeholder="Hasil/rencana tindak lanjut"></textarea><button class="btn btn-accent w-full">Tambah tindak lanjut</button></form>@endcan</section>
@can('update',$case)<section class="card card-body"><h2 class="text-lg font-bold">Administrasi</h2><div class="mt-4 grid gap-2"><a class="btn btn-secondary" href="{{ route('documents.create',['student'=>$case->student_id,'case'=>$case->id]) }}">Buat surat/dokumen</a><a class="btn btn-secondary" href="{{ route('home-visits.create',['student'=>$case->student_id]) }}">Buat laporan home visit</a></div></section>
<section class="card card-body"><h2 class="text-lg font-bold">Status kasus</h2><form method="post" action="{{ route('cases.status',$case) }}" class="mt-4 space-y-3">@csrf @method('put')<select class="form-select" name="status">@foreach(\App\Enums\CaseStatus::cases() as $status)<option value="{{ $status->value }}" @selected($case->status===$status)>{{ $status->label() }}</option>@endforeach</select><textarea class="form-control" name="reason" rows="2" placeholder="Alasan wajib jika dibatalkan"></textarea><button class="btn btn-primary w-full">Perbarui status</button></form></section>@endcan</div></div>
@endsection
