@extends('layouts.app')
@section('title', 'Data Siswa')
@section('content')
<header class="page-header">
    <div><p class="page-eyebrow"><x-icon name="students" class="size-4" /> Direktori sekolah</p><h1 class="page-title">Data siswa</h1><p class="page-description">Temukan siswa dengan cepat melalui nama, NIS, NISN, ID sementara, kelas, atau status.</p></div>
    @if(auth()->user()->hasRole(\App\Enums\UserRole::SuperAdmin, \App\Enums\UserRole::Coordinator))<a class="btn btn-secondary" href="{{ route('imports.index') }}"><x-icon name="upload" /> Impor Excel</a>@endif
</header>
<form data-auto-filter-form class="card card-body mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-[minmax(280px,1fr)_240px_180px_auto]">
    <div><label class="form-label" for="student-search">Cari siswa</label><div class="input-with-icon"><x-icon name="search" /><input id="student-search" class="form-control" name="q" value="{{ request('q') }}" placeholder="Ketik sebagian nama, NIS, NISN, atau ID..."></div><p class="field-help">Pencarian berjalan 2 detik setelah selesai mengetik.</p></div>
    <div><label class="form-label" for="class_id">Kelas</label><select id="class_id" class="form-select" name="class_id"><option value="">Semua kelas</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected(request('class_id') == $class->id)>{{ $class->name }} — {{ $class->academicYear->name }}</option>@endforeach</select></div>
    <div><label class="form-label" for="student-status">Status</label><select id="student-status" class="form-select" name="status"><option value="">Semua status</option>@foreach(\App\Enums\StudentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
    <button class="btn btn-primary self-end"><x-icon name="search" /> Cari siswa</button>
</form>
<div class="card overflow-hidden"><div class="table-wrap"><table class="table"><thead><tr><th>Nama siswa</th><th>Identitas</th><th>Kelas</th><th>Status</th><th><span class="sr-only">Aksi</span></th></tr></thead><tbody>@forelse($students as $student)<tr><td><div class="flex items-center gap-3"><span class="student-avatar">{{ mb_strtoupper(mb_substr($student->name, 0, 1)) }}</span><div><strong>{{ $student->name }}</strong><p class="mt-1 text-xs text-slate-400">{{ $student->gender === 'L' ? 'Laki-laki' : 'Perempuan' }}</p></div></div></td><td><p class="font-semibold text-slate-700">NISN: {{ $student->nisn ?? '-' }}</p><p class="mt-1 text-xs text-slate-400">NIS: {{ $student->nis ?? '-' }} · {{ $student->temporary_id }}</p></td><td>{{ $student->currentEnrollment?->schoolClass?->name ?? '-' }}</td><td><span class="badge badge-{{ $student->status->value === 'active' ? 'emerald' : 'slate' }}">{{ $student->status->label() }}</span></td><td class="text-right"><a class="btn btn-secondary" href="{{ route('students.show', $student) }}">Buka <x-icon name="arrow-right" /></a></td></tr>@empty<tr><td colspan="5"><div class="empty-state"><x-icon name="search" class="mx-auto mb-3 size-8" /><p>Data siswa tidak ditemukan.</p></div></td></tr>@endforelse</tbody></table></div></div>
<div class="mt-5">{{ $students->links() }}</div>
@endsection
